# Generated by Django 5.0.7 on 2024-07-25 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopicModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('PR', 'Programming'), ('TC', 'Technology'), ('AT', 'Art'), ('DO', 'DevOps'), ('LT', 'Literature'), ('SC', 'Science')], max_length=2)),
                ('posts', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='blogmodel',
            name='topics',
            field=models.CharField(choices=[('PR', 'Programming'), ('TC', 'Technology'), ('AT', 'Art'), ('DO', 'DevOps'), ('LT', 'Literature'), ('SC', 'Science')], max_length=2),
        ),
    ]
